#!/usr/bin/env python3
"""Assemble verified clips + voiceover into the final chapter video.

Usage:
    python assemble.py --order ch1_order.txt --voiceover ch1-vo.mp3 --out ch1.mp4

ch1_order.txt lists clip filenames in sequence, one per line.
Clips must share codec/resolution (they will if generated by generate_clips.py).
"""
import argparse
import subprocess
import sys
from pathlib import Path


def probe_duration(p: Path) -> float:
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", str(p)],
        capture_output=True, text=True, check=True)
    return float(r.stdout.strip())


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--order", required=True, help="text file: clip paths in order")
    ap.add_argument("--voiceover", required=True, help="narration mp3")
    ap.add_argument("--out", required=True)
    ap.add_argument("--vo-delay-ms", type=int, default=800)
    args = ap.parse_args()

    clips = [Path(l.strip()) for l in Path(args.order).read_text().splitlines() if l.strip()]
    missing = [c for c in clips if not c.exists()]
    if missing:
        sys.exit(f"Missing clips: {missing}")
    vo = Path(args.voiceover)
    if not vo.exists():
        sys.exit(f"Missing voiceover: {vo}")

    filelist = Path("_assemble_list.txt")
    filelist.write_text("".join(f"file '{c.resolve()}'\n" for c in clips))

    vo_dur, vid_dur = probe_duration(vo), sum(probe_duration(c) for c in clips)
    print(f"Video: {vid_dur:.1f}s  Voiceover: {vo_dur:.1f}s")
    if vo_dur > vid_dur:
        print("WARNING: voiceover is longer than the video — add more clips or "
              "the narration will be cut.", file=sys.stderr)

    # Concat (stream copy), then lay the voiceover over the full length.
    # apad + -shortest: narration plays once, then silence to the end of video.
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error",
         "-f", "concat", "-safe", "0", "-i", str(filelist),
         "-i", str(vo),
         "-filter_complex",
         f"[1:a]adelay={args.vo_delay_ms}|{args.vo_delay_ms},apad[a]",
         "-map", "0:v", "-map", "[a]",
         "-c:v", "copy", "-c:a", "aac", "-shortest",
         args.out],
        check=True,
    )
    filelist.unlink()
    print(f"Wrote {args.out} ({probe_duration(Path(args.out)):.1f}s)")


if __name__ == "__main__":
    main()
